name: Build and Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: flask_app
          push: true
          tags: hrushikeshdidhe/flask_app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > /tmp/ssh_key.pem
          chmod 600 /tmp/ssh_key.pem

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key_path: /tmp/ssh_key.pem
          script: |
            sudo docker pull hrushikeshdidhe/flask_app:latest
            sudo docker stop flask-app || true
            sudo docker rm flask-app || true
            sudo docker run -d -p 5000:5000 --name flask-app hrushikeshdidhe/flask_app:latest
