name: Build and Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.hrushikeshdidhe }}
          password: ${{ secrets.Didhe@123 }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: yourusername/your-repo:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.ec2-65-0-61-75.ap-south-1.compute.amazonaws.com }}
          username: ${{ secrets.ubuntu }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull yourusername/your-repo:latest
            docker stop flask-app || true
            docker run -d -p 5000:5000 --name flask-app yourusername/your-repo:latest
